version: "3.8"

services:
    coldfusion:
        container_name: coldfusion
        build:
            context: ./app
            dockerfile: Dockerfile
        image: app
        depends_on:
            - addons
        ports:
            - "8500:8500"
        volumes:
            - "./app:/app"
            - "./cflogs:/opt/coldfusion/cfusion/logs"
        env_file:
            - config/coldfusion.env
        healthcheck:
            test: curl -f http://addons:8989/solr/ || exit 1
            interval: 1m
            timeout: 3s
        deploy:
            # mode: replicated
            # replicas: 2
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
        networks:
            - cfCustomLoggerNet

    addons:
        container_name: cfAddons
        image: eaps-docker-coldfusion.bintray.io/cf/addons:latest-2018
        environment:
            - acceptEULA=YES
        ports:
            - "8989:8989"
        networks:
            - cfCustomLoggerNet

    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - "./database/mysql_data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "password"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - cfCustomLoggerNet

    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6381:6379"
        volumes:
            - "./database/redis_data:/data"
        networks:
            - cfCustomLoggerNet

    pmt:
        container_name: cfPMT
        image: eaps-docker-coldfusion.bintray.io/cf/pmt:latest-2018
        depends_on:
            - coldfusion
        ports:
            - "9101:9101"
        env_file:
            - config/pmt.env
        healthcheck:
            test: curl -f http://localhost:9101/
            interval: 1m
            timeout: 3s
        networks:
            - cfCustomLoggerNet

volumes:
    redis_data:
    app_data:
    cf_root:
    mysql:

networks:
    cfCustomLoggerNet:
